name: GitHub Actions Secrets
on:
  push:
    branches: [ main ]
jobs: 
     secrets-in-github-latest:
      runs-on: ubuntu-latest
      # The Secrets Action GitHub example has three steps
      steps: 
        # Show how to print GitHub secrets to the console 
      - name: Step 1 - Echo out a GitHub Action Secret to the logs
        run: |
          echo "The GitHub Action Secrets will be masked:  "
          echo ${{ secrets.SECRET_TOKEN}} >> secret.txt
          echo "Trick to echo GitHub Action Secret:  "
          echo ${{ secrets.SECRET_TOKEN}} | sed 's/./& /g' 
          cat secret.txt
      # Use a GitHub Action secret variable in a bash shell
      - name: Step 2 - GitHub Action If statement (true)
        env: 
          WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN}}
        if: env.WHO_TO_TRUST == 'TrustNo1'
        run: echo "I know what the secret token is!"
      # A GitHub Action if statement with a secret environment variable 
      - name: Step 3 - conditional GitHub Action (false)
        shell: bash
        env:
          WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN}}
        if: env.WHO_TO_TRUST != 'TrustNobody'
        run: echo "I was wrong thinking the GitHub secret was 'TrustNobody'!"
